//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:20:21 PM CET 
//


package com.ftn.model.dto.statementaccountinquiry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="statement_account_inquiry" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statementAccountInquiry"
})
@XmlRootElement(name = "getStatementAccountInquiryResponse")
public class GetStatementAccountInquiryResponse {

    @XmlElement(name = "statement_account_inquiry", required = true)
    protected String statementAccountInquiry;

    /**
     * Gets the value of the statementAccountInquiry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatementAccountInquiry() {
        return statementAccountInquiry;
    }

    /**
     * Sets the value of the statementAccountInquiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatementAccountInquiry(String value) {
        this.statementAccountInquiry = value;
    }

}
