//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:20:21 PM CET 
//


package com.ftn.statementaccountinquiry;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.statementaccountinquiry package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.statementaccountinquiry
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetStatementAccountInquiryRequest }
     * 
     */
    public GetStatementAccountInquiryRequest createGetStatementAccountInquiryRequest() {
        return new GetStatementAccountInquiryRequest();
    }

    /**
     * Create an instance of {@link StatementAccountInquiry }
     * 
     */
    public StatementAccountInquiry createStatementAccountInquiry() {
        return new StatementAccountInquiry();
    }

    /**
     * Create an instance of {@link GetStatementAccountInquiryResponse }
     * 
     */
    public GetStatementAccountInquiryResponse createGetStatementAccountInquiryResponse() {
        return new GetStatementAccountInquiryResponse();
    }

}
