//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:30:54 PM CET 
//


package com.ftn.section;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.ftn.sectionheader.SectionHeader;
import com.ftn.sectionitem.SectionItem;


/**
 * <p>Java class for section complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="section"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.ftn.com/sectionHeader}section_header"/&gt;
 *         &lt;element ref="{http://www.ftn.com/sectionItem}section_item" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "section", propOrder = {
    "sectionHeader",
    "sectionItem"
})
public class Section {

    @XmlElement(name = "section_header", namespace = "http://www.ftn.com/sectionHeader", required = true)
    protected SectionHeader sectionHeader;
    @XmlElement(name = "section_item", namespace = "http://www.ftn.com/sectionItem", required = true)
    protected List<SectionItem> sectionItem;

    /**
     * Gets the value of the sectionHeader property.
     * 
     * @return
     *     possible object is
     *     {@link SectionHeader }
     *     
     */
    public SectionHeader getSectionHeader() {
        return sectionHeader;
    }

    /**
     * Sets the value of the sectionHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link SectionHeader }
     *     
     */
    public void setSectionHeader(SectionHeader value) {
        this.sectionHeader = value;
    }

    /**
     * Gets the value of the sectionItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sectionItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSectionItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SectionItem }
     * 
     * 
     */
    public List<SectionItem> getSectionItem() {
        if (sectionItem == null) {
            sectionItem = new ArrayList<SectionItem>();
        }
        return this.sectionItem;
    }

}
