//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:02:25 PM CET 
//


package com.ftn.types;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TWarrantData }
     * 
     */
    public TWarrantData createTWarrantData() {
        return new TWarrantData();
    }

    /**
     * Create an instance of {@link TBankData }
     * 
     */
    public TBankData createTBankData() {
        return new TBankData();
    }

    /**
     * Create an instance of {@link TItemInvoice }
     * 
     */
    public TItemInvoice createTItemInvoice() {
        return new TItemInvoice();
    }

    /**
     * Create an instance of {@link TSubjectData }
     * 
     */
    public TSubjectData createTSubjectData() {
        return new TSubjectData();
    }

    /**
     * Create an instance of {@link TCorporateBody }
     * 
     */
    public TCorporateBody createTCorporateBody() {
        return new TCorporateBody();
    }

    /**
     * Create an instance of {@link TPaymentData }
     * 
     */
    public TPaymentData createTPaymentData() {
        return new TPaymentData();
    }

    /**
     * Create an instance of {@link TTransferParticipiant }
     * 
     */
    public TTransferParticipiant createTTransferParticipiant() {
        return new TTransferParticipiant();
    }

    /**
     * Create an instance of {@link TDataTransfer }
     * 
     */
    public TDataTransfer createTDataTransfer() {
        return new TDataTransfer();
    }

    /**
     * Create an instance of {@link TChanges }
     * 
     */
    public TChanges createTChanges() {
        return new TChanges();
    }

    /**
     * Create an instance of {@link TWarrantData.Amount }
     * 
     */
    public TWarrantData.Amount createTWarrantDataAmount() {
        return new TWarrantData.Amount();
    }

}
