//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:02:25 PM CET 
//


package com.ftn.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TCurrencyLabel.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TCurrencyLabel"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;pattern value="[A-Z]{3}"/&gt;
 *     &lt;enumeration value="RSD"/&gt;
 *     &lt;enumeration value="EUR"/&gt;
 *     &lt;enumeration value="USD"/&gt;
 *     &lt;enumeration value="CHF"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TCurrencyLabel")
@XmlEnum
public enum TCurrencyLabel {

    RSD,
    EUR,
    USD,
    CHF;

    public String value() {
        return name();
    }

    public static TCurrencyLabel fromValue(String v) {
        return valueOf(v);
    }

}
