//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:02:25 PM CET 
//


package com.ftn.model.dto.types;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TDataTransfer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDataTransfer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="debtor" type="{http://www.ftn.com/types}TTransferParticipiant"/&gt;
 *         &lt;element name="creditor" type="{http://www.ftn.com/types}TTransferParticipiant"/&gt;
 *         &lt;element name="amount"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.ftn.com/types}TAmount"&gt;
 *               &lt;totalDigits value="15"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="currency_label" type="{http://www.ftn.com/types}TCurrencyLabel" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDataTransfer", propOrder = {

})
public class TDataTransfer {

    @XmlElement(required = true)
    protected TTransferParticipiant debtor;
    @XmlElement(required = true)
    protected TTransferParticipiant creditor;
    @XmlElement(required = true)
    protected BigDecimal amount;
    @XmlAttribute(name = "currency_label")
    protected TCurrencyLabel currencyLabel;

    /**
     * Gets the value of the debtor property.
     * 
     * @return
     *     possible object is
     *     {@link TTransferParticipiant }
     *     
     */
    public TTransferParticipiant getDebtor() {
        return debtor;
    }

    /**
     * Sets the value of the debtor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransferParticipiant }
     *     
     */
    public void setDebtor(TTransferParticipiant value) {
        this.debtor = value;
    }

    /**
     * Gets the value of the creditor property.
     * 
     * @return
     *     possible object is
     *     {@link TTransferParticipiant }
     *     
     */
    public TTransferParticipiant getCreditor() {
        return creditor;
    }

    /**
     * Sets the value of the creditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransferParticipiant }
     *     
     */
    public void setCreditor(TTransferParticipiant value) {
        this.creditor = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the currencyLabel property.
     * 
     * @return
     *     possible object is
     *     {@link TCurrencyLabel }
     *     
     */
    public TCurrencyLabel getCurrencyLabel() {
        return currencyLabel;
    }

    /**
     * Sets the value of the currencyLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCurrencyLabel }
     *     
     */
    public void setCurrencyLabel(TCurrencyLabel value) {
        this.currencyLabel = value;
    }

}
