//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:02:25 PM CET 
//


package com.ftn.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTransferParticipiant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTransferParticipiant"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="participiant_account" type="{http://www.ftn.com/types}TAccountNumber"/&gt;
 *         &lt;element name="transfer_model" type="{http://www.ftn.com/types}TModel"/&gt;
 *         &lt;element name="reference_number" type="{http://www.ftn.com/types}TReferenceNumber"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTransferParticipiant", propOrder = {

})
public class TTransferParticipiant {

    @XmlElement(name = "participiant_account", required = true)
    protected String participiantAccount;
    @XmlElement(name = "transfer_model")
    @XmlSchemaType(name = "unsignedInt")
    protected long transferModel;
    @XmlElement(name = "reference_number", required = true)
    protected String referenceNumber;

    /**
     * Gets the value of the participiantAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticipiantAccount() {
        return participiantAccount;
    }

    /**
     * Sets the value of the participiantAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticipiantAccount(String value) {
        this.participiantAccount = value;
    }

    /**
     * Gets the value of the transferModel property.
     * 
     */
    public long getTransferModel() {
        return transferModel;
    }

    /**
     * Sets the value of the transferModel property.
     * 
     */
    public void setTransferModel(long value) {
        this.transferModel = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Sets the value of the referenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNumber(String value) {
        this.referenceNumber = value;
    }

}
