spring:
    datasource:
        url: jdbc:mysql://localhost:3306/isurebank2?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: root

    jpa:
        show_sql: true
        hibernate:
            ddl-auto: update
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                hbm2ddl:
                  import_files: init2.sql

environment:
    swiftCode: VBUBRS22
    nbsUrl: http://localhost:8094/ws
    selfUrl: http://192.168.0.12:9020/
    concentratorUrl: http://192.168.0.14:9035/
    pccUrl: http://192.168.0.12:9025/pcc
    bankName: Verybusy bank