spring:
    datasource:
        url: jdbc:mysql://localhost:3306/pcc?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: root

    jpa:
        show_sql: true
        hibernate:
            ddl-auto: create
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                hbm2ddl:
                  import_files: insert.sql

environment:
  acquirerUrl: http://192.168.0.12:9015/
  issuerUrl: http://192.168.0.12:9020/
  acquirerPort: 9015
  issuerPort: 9020