//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:14:26 PM CET 
//


package com.ftn.model.dto.mt900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.ftn.model.dto.types.TBankData;
import com.ftn.model.dto.types.TWarrantData;


/**
 * <p>Java class for mt900 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mt900"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="debtor_bank_data" type="{http://www.ftn.com/types}TBankData"/&gt;
 *         &lt;element name="warrant_data"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.ftn.com/types}TWarrantData"&gt;
 *                 &lt;attribute name="warrant_message_id"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;maxLength value="50"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="message_id"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;maxLength value="50"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mt900", propOrder = {
    "debtorBankData",
    "warrantData"
})
public class Mt900 {

    @XmlElement(name = "debtor_bank_data", required = true)
    protected TBankData debtorBankData;
    @XmlElement(name = "warrant_data", required = true)
    protected Mt900 .WarrantData warrantData;
    @XmlAttribute(name = "message_id")
    protected String messageId;

    /**
     * Gets the value of the debtorBankData property.
     * 
     * @return
     *     possible object is
     *     {@link TBankData }
     *     
     */
    public TBankData getDebtorBankData() {
        return debtorBankData;
    }

    /**
     * Sets the value of the debtorBankData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBankData }
     *     
     */
    public void setDebtorBankData(TBankData value) {
        this.debtorBankData = value;
    }

    /**
     * Gets the value of the warrantData property.
     * 
     * @return
     *     possible object is
     *     {@link Mt900 .WarrantData }
     *     
     */
    public Mt900 .WarrantData getWarrantData() {
        return warrantData;
    }

    /**
     * Sets the value of the warrantData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mt900 .WarrantData }
     *     
     */
    public void setWarrantData(Mt900 .WarrantData value) {
        this.warrantData = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.ftn.com/types}TWarrantData"&gt;
     *       &lt;attribute name="warrant_message_id"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;maxLength value="50"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class WarrantData
        extends TWarrantData
    {

        @XmlAttribute(name = "warrant_message_id")
        protected String warrantMessageId;

        /**
         * Gets the value of the warrantMessageId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWarrantMessageId() {
            return warrantMessageId;
        }

        /**
         * Sets the value of the warrantMessageId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWarrantMessageId(String value) {
            this.warrantMessageId = value;
        }

    }

}
